[package]
name = "lemcom-api"
version = "0.1.2"
edition = "2021"

[dependencies]
axum = "0.7.5"
chrono = "0.4.37"
dotenvy = "0.15.7"
mongodb = "2.8.2"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
